resources:
- manifests.yaml

configurations:
- kustomizeconfig.yaml

patches:
  - path: patches/operator-exclusion.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration