name: 'Upgrade integration test'
description: 'Runs upgrade suite of integration tests'
inputs:
  upgrade-image-name:
    description: 'Image that will api-gateway be upgraded to'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - name: Add local.kyma.dev to /etc/hosts
      shell: bash
      run: |
        sudo echo "127.0.0.1 local.kyma.dev" | sudo tee -a /etc/hosts
    - name: Run upgrade integration test
      env:
        KYMA_DOMAIN: "local.kyma.dev"
        TEST_UPGRADE_IMG: ${{ inputs.upgrade-image-name }}
      run: |
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | sudo bash
        sudo curl -Lo /usr/bin/kyma https://storage.googleapis.com/kyma-cli-unstable/kyma-linux
        sudo chmod +x /usr/bin/kyma
        sudo kyma provision k3d
        KUBECONFIG=$(k3d kubeconfig merge kyma) EXPORT_RESULT=true make install-kyma test-upgrade
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: html-reports
        path: tests/integration/reports/
