apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

# Remove CRDs that belong to a feature that is not released.
patchesStrategicMerge:
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: ratelimits.ratelimit.kyma-project.io
    $patch: delete
