version: 2
updates:
  # main branch configuration
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io/*"
    ignore:
      - dependency-name: "*"
        versions:
          - "*-alpha"
          - "*-beta"
          - "*-unstable"
      - dependency-name: "istio.io/client-go"
      - dependency-name: "istio.io/api"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
    ignore:
      - dependency-name: "*"
        versions:
          - "*-alpha"
          - "*-beta"
          - "*-unstable"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "*"
        versions:
          - "*-alpha"
          - "*-beta"
          - "*-unstable"

  - package-ecosystem: "npm"
    directory: "/tests/ui/tests/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        versions:
          - "*-alpha"
          - "*-beta"
          - "*-unstable"

  # release branch configuration
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-3.1"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io/*"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "*"
        versions:
          - "*-alpha"
          - "*-beta"
          - "*-unstable"
      - dependency-name: "istio.io/client-go"
      - dependency-name: "istio.io/api"

  - package-ecosystem: "docker"
    target-branch: "release-3.1"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "*"
        versions:
          - "*-alpha"
          - "*-beta"
          - "*-unstable"
