name: 'Integration tests (Gardener)'
description: 'Runs integration tests on Gardener'
inputs:
  manager_image:
    description: "Manager image used for test"
    required: true
  gardener_secret:
    description: "Kubeconfig secret for Gardener"
    required: true
  script:
    description: "Entry point script for test"
    required: true
  test_make_target:
    description: 'Make target for integration tests to run'
    default: 'test-custom-domain test-integration-gateway'
  client_id:
    description: "Client id for oidc"
    required: false
  client_secret:
    description: "Client secret for oidc"
    required: false
  oidc_well_known_url:
    description: "OIDC well known URL"
    required: false
  dns_secret_json:
    description: "Secret json for DNS provider"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Checkout to PR branch # to remove after getting rid of pull_request_target
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      run: |
        git fetch origin pull/${{ github.event.number }}/head:PR-${{ github.event.number }}
        git checkout PR-${{ github.event.number }}
    - name: Prepare gardener kubeconfig
      shell: bash
      env:
        GARDENER_TOKEN: ${{ inputs.gardener_secret }}
      run: |
        ./hack/ci/gardener_kubeconfig.sh
    - name: Prepare DNS SA secret
      shell: bash
      env:
        DNS_SA_BASE64: ${{ inputs.dns_secret_json }}
      run: |
        echo "$DNS_SA_BASE64" | base64 --decode >> service-account.json
    - name: Run integration tests
      shell: bash
      env:
        IMG: ${{ inputs.manager_image }}
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
        OIDC_CONFIG_URL: ${{ inputs.oidc_well_known_url }}
        TEST_SA_ACCESS_KEY_PATH: "${{ github.workspace }}/service-account.json"
        GARDENER_KUBECONFIG: "gardener_kubeconfig.yaml"
        PERSISTENT_CLUSTER_KUBECONFIG: "cluster_kubeconfig.yaml"
      run: |
        EXPORT_RESULT=true \
        ${{ inputs.script }} ${{ inputs.test_make_target }}
    - name: Gather deployment logs
      shell: bash
      env:
        PERSISTENT_CLUSTER_KUBECONFIG: "cluster_kubeconfig.yaml"
      if: failure()
      run: |
        mkdir logs
        export KUBECONFIG="${PERSISTENT_CLUSTER_KUBECONFIG}"
        (kubectl logs -n kyma-system deployments/istio-controller-manager || true) > logs/istio-controller-manager.log
        (kubectl logs -n kyma-system deployments/api-gateway-controller-manager || true) > logs/api-gateway-controller-manager.log
        (kubectl logs -n istio-system deployments/istio-ingressgateway || true) > logs/istio-ingressgateway.log
        (kubectl logs -n istio-system deployments/istiod || true) > logs/istiod.log
        (kubectl logs -n kyma-system deployments/ory-oathkeeper || true) > logs/ory-oathkeeper.log
        (kubectl get --all-namespaces apirules.gateway.kyma-project.io -oyaml || true) > logs/apirules-dump.yaml
        (kubectl get --all-namespaces apigateways.operator.kyma-project.io -oyaml || true) > logs/gateway-dump.yaml
        (kubectl get -n kyma-system deployment ory-oathkeeper -oyaml || true) > logs/ory-oathkeeper-dump.yaml
    - name: Uploads logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-${{ github.job }}-${{ inputs.test_make_target }}
        path: logs/
    - name: Uploads artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-reports-${{ github.job }}-${{ inputs.test_make_target }}
        path: tests/integration/reports/
