name: 'Integration tests (Gardener)'
description: 'Runs integration tests on Gardener'
inputs:
  manager_image:
    description: "Manager image used for test"
    required: true
  gardener_secret:
    description: "Kubeconfig secret for Gardener"
    required: true
  script:
    description: "Entry point script for test"
    required: true
  client_id:
    description: "Client id for oidc"
    required: true
  client_secret:
    description: "Client secret for oidc"
    required: true
  oidc_issuer_url:
    description: "OIDC issuer url"
    required: true
  dns_secret_json:
    description: "Secret json for DNS provider"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Checkout to PR branch # to remove after getting rid of pull_request_target
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      run: |
        git fetch origin pull/${{ github.event.number }}/head:PR-${{ github.event.number }}
        git checkout PR-${{ github.event.number }}
    - name: Prepare gardener kubeconfig
      shell: bash
      env:
        GARDENER_TOKEN: ${{ inputs.gardener_secret }}
      run: |
        ./hack/ci/gardener_kubeconfig.sh
    - name: Prepare DNS SA secret
      shell: bash
      run: |
        echo "${{ inputs.dns_secret_json }}" >> service-account.json
    - name: Run integration tests
      shell: bash
      env:
        IMG: ${{ inputs.manager_image }}
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
        OIDC_ISSUER_URL: ${{ inputs.oidc_issuer_url }}
        TEST_SA_ACCESS_KEY_PATH: "service-account.json"
        GARDENER_KUBECONFIG: "gardener_kubeconfig.yaml"
      run: |
        EXPORT_RESULT=true \
        ${{ inputs.script }}
    - name: Uploads artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-reports-${{ github.job }}
        path: tests/integration/reports/
