# Documentation for how to configure goreleaser can be found at http://goreleaser.com
project_name: api-gateway
release:
  github:
    owner: kyma-project
    name: api-gateway
  prerelease: auto
  header: |
    Images published in {{ .Tag }} release:
    - [https://eu.gcr.io/kyma-project/api-gateway-controller:{{ .Tag }}](https://eu.gcr.io/kyma-project/api-gateway-controller:{{ .Tag }})
    - [https://eu.gcr.io/kyma-project/api-gateway-webhook-certificates:{{ .Tag }}](https://eu.gcr.io/kyma-project/api-gateway-webhook-certificates:{{ .Tag }})
builds:
- env:
  - CGO_ENABLED=0
  main: ./
  goos:
    - darwin
    - linux
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
env_files:
  github_token: /etc/github/token
