resources:
- manager.yaml
- metrics_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: europe-docker.pkg.dev/kyma-project/dev/api-gateway-manager
  newTag: PR-812
