resources:
- jobs.yaml
- rbac.yaml

namespace: kyma-system

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: init-certificates
  newName: kyma-project/api-gateway-webhook-certificates
  newTag: latest