# To modify the message content go to Slack workflow in #goat-int channel

name: 'Slack notification on failed workflow'
description: 'Sends slack notification on failed workflow'
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack workflow webhook url'
    required: true
runs:
  using: "composite"
  steps:
    - name: Notify
      uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
      with:
        webhook: ${{ inputs.SLACK_WEBHOOK_URL }}
        webhook-type: webhook-trigger
        payload-templated: true
        payload: |
          repository: ${{ github.repository }},
          workflow: ${{ github.workflow }},
          owner: ${{ github.actor }}
          attempt: ${{ github.run_number }}
          link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
