apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-api-gateway-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - gateway.kyma-project.io
  resources:
  - apirules
  - ratelimits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.kyma-project.io
  resources:
  - apirules/status
  - ratelimits/status
  verbs:
  - get
- apiGroups:
    - operator.kyma-project.io
  resources:
    - apigateways
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - operator.kyma-project.io
  resources:
    - apigateways/status
  verbs:
    - get
