# permissions for end users to view apigateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apigateway-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apirule-v2
    app.kubernetes.io/part-of: apirule-v2
    app.kubernetes.io/managed-by: kustomize
  name: apigateway-viewer-role
rules:
- apiGroups:
  - gateway.kyma-project.io
  resources:
  - apigateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.kyma-project.io
  resources:
  - apigateways/status
  verbs:
  - get
