apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
  labels:
    app.kubernetes.io/component: operator
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
