resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- apigateway_editor_role.yaml
- apigateway_viewer_role.yaml
- apigateway_admin_role.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml

labels:
  - pairs:
      app.kubernetes.io/component: operator