# permissions for end users to view ratelimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ratelimit-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: api-gateway
    app.kubernetes.io/part-of: api-gateway
    app.kubernetes.io/managed-by: kustomize
  name: ratelimit-viewer-role
rules:
- apiGroups:
  - ratelimit.kyma-project.io
  resources:
  - ratelimits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.kyma-project.io
  resources:
  - ratelimits/status
  verbs:
  - get
