envs=$(sed -n '/bdba:/,/mend:/p' sec-scanners-config.yaml | grep "\- " | sed 's/.*- //g' | \
      grep -v 'api-gateway-manager' | \
      while read -r img; do
        var_name=$(basename "$img" | sed -r 's/\w\///g' | sed 's/\:.*//g')
        echo "- name: $var_name"
        echo "  value: $img"
      done)

envs=$(echo "$envs" | sed 's/^/            /')

cat <<EOF > config/manager/env-images.yaml
# Generated by hack/generate_sec_scanners_images_env.sh
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/component: api-gateway-operator.kyma-project.io
    control-plane: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
$envs
EOF
