apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi2
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["exit", "1"]
      restartPolicy: Never
  backoffLimit: 4



