apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ory
      app.kubernetes.io/name: oathkeeper