name: 'Integration test - upgrade (k3d)'
description: 'Runs integration tests - upgrade on k3d'
inputs:
  manager_image:
    description: 'Manager image used for test'
    required: true
  client_id:
    description: "Client id for oidc"
    required: false
  client_secret:
    description: "Client secret for oidc"
    required: false
  oidc_well_known_url:
    description: "OIDC well known URL"
    required: false
  target_branch:
    description: 'Target branch'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Checkout to PR branch # to remove after getting rid of pull_request_target
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      run: |
        git fetch origin pull/${{ github.event.number }}/head:PR-${{ github.event.number }}
        git checkout PR-${{ github.event.number }}
    - name: Create Cluster
      shell: bash
      run: |
    - name: Create Cluster
      uses: ./.github/actions/provision-k3d-cluster
      with:
        version: "1.29.7"
    - name: Run test
      shell: bash
      env:
        KYMA_DOMAIN: "local.kyma.dev"
        TEST_UPGRADE_IMG: ${{ inputs.manager_image }}
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
        OIDC_CONFIG_URL: ${{ inputs.oidc_well_known_url }}
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          k3d image import ${{ inputs.manager_image }} -c k3s-default
        fi
        kubectl config use-context k3d-k3s-default
        EXPORT_RESULT=true TARGET_BRANCH=${{inputs.target_branch}} make test-upgrade
    - name: Uploads artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-reports-${{ github.job }}
        path: tests/integration/reports/
