apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    kyma-project.io/module: api-gateway
spec:
  secretName: {{.SecretName}}
  commonName: "*.{{.Domain}}"