apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    app.kubernetes.io/name: api-gateway-operator
    app.kubernetes.io/instance: api-gateway-operator-default
    app.kubernetes.io/version: "{{.Version}}"
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: api-gateway
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{.CertificateSecretName}}
    hosts:
      - "*.{{.Domain}}"
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true # automatic 301 redirect from http to https
    hosts:
      - "*.{{.Domain}}"
