apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    kyma-project.io/module: api-gateway
spec:
  hosts:
    - "healthz.{{.Domain}}"
  gateways:
    - "{{.Gateway}}"
  http:
    - match:
        - uri:
            exact: /healthz/ready
      route:
        - destination:
            port:
              number: 15021
            host: istio-ingressgateway.istio-system.svc.cluster.local
