apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  hosts:
    - "*.{{.Domain}}"
  gateways:
    - "{{.Gateway}}"
  http:
    - match:
        - uri:
            exact: /healthz/ready
      route:
        - destination:
            port:
              number: {{.Port}}
            host: "{{.IngressGateway}}"
