name: 'Load Istio Manager Image'
description: 'Load Istio manage image from a tar archive in the artifacts'
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: manager-image
        path: /tmp
    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/manager-image.tar
