apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    dns.gardener.cloud/class: garden
spec:
  dnsName: "*.{{.Domain}}"
  ttl: 600
  targets:
    - {{.IngressGatewayServiceIp}}