apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  - patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - gateway.kyma-project.io
          resources:
            - ratelimits
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: manager-role
  - patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - gateway.kyma-project.io
          resources:
            - ratelimits/finalizers
          verbs:
            - update
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: manager-role
  - patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - gateway.kyma-project.io
          resources:
            - ratelimits/status
          verbs:
            - get
            - patch
            - update
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: manager-role