name: 'Provision k3d cluster'
description: 'Provisions a k3d cluster'
inputs:
  version:
    description: 'Kubernetes version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Provision k3d cluster
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        k3d cluster create --agents 2 \
                           --image docker.io/rancher/k3s:v${{ inputs.version }}-k3s1 \
                           --servers-memory=16g \
                           --port 80:80@loadbalancer \
                           --port 443:443@loadbalancer \
                           --k3s-arg "--disable=traefik@server:0"