{{ if .Values.istioJWT.enabled }}
apiVersion: v1                        
kind: ConfigMap   
metadata:
   namespace: kyma-system
   name: api-gateway-config
data:        
   api-gateway-config: >  
     jwtHandler: "istio"
{{ end }}