apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    kyma-project.io/module: api-gateway
    app.kubernetes.io/managed-by: api-gateway
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: api-gateway
    externalgateway.gateway.kyma-project.io/name: {{.ExternalGatewayName}}
    externalgateway.gateway.kyma-project.io/namespace: {{.ExternalGatewayNamespace}}
spec:
  secretName: {{.SecretName}}
  commonName: "*.{{.Domain}}"
  dnsNames:
    - "*.{{.Domain}}"
  issuerRef:
    name: garden
  privateKey:
    size: 4096