apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    dns.gardener.cloud/class: garden
  labels:
    app.kubernetes.io/managed-by: externalgateway-controller
    app.kubernetes.io/created-for: {{.CreatedFor}}
    gateway.kyma-project.io/external-id: {{.ExternalGatewayName}}
spec:
  dnsName: "*.{{.Domain}}"
  ttl: 600
  targets:
    - {{.IngressGatewayServiceIp}}