name: 'Integration tests (k3d)'
description: 'Runs integration tests on k3d'
inputs:
  manager_image:
    description: 'Manager image used for test'
    required: true
  client_id:
    description: "Client id for oidc"
    required: false
  client_secret:
    description: "Client secret for oidc"
    required: false
  oidc_well_known_url:
    description: "OIDC well known URL"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Checkout to PR branch # to remove after getting rid of pull_request_target
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      run: |
        git fetch origin pull/${{ github.event.number }}/head:PR-${{ github.event.number }}
        git checkout PR-${{ github.event.number }}
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "k3d-cluster"
        args: >-
          --agents 0
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --k3s-arg "--disable=traefik@server:0"
    - name: Run integration tests
      shell: bash
      env:
        KYMA_DOMAIN: "local.kyma.dev"
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
        OIDC_CONFIG_URL: ${{ inputs.oidc_well_known_url }}
        IMG: ${{ inputs.manager_image }}
      run: |
        EXPORT_RESULT=true \
        make install-istio deploy test-integration
    - shell: bash
      name: gather deployment logs
      if: failure()
      run: |
        mkdir logs
        (kubectl logs -n kyma-system deployments/istio-controller-manager || true) > logs/istio-controller-manager.log
        (kubectl logs -n kyma-system deployments/api-gateway-controller-manager || true) > logs/api-gateway-controller-manager.log
        (kubectl logs -n istio-system deployments/istio-ingressgateway || true) > logs/istio-ingressgateway.log
        (kubectl logs -n istio-system deployments/istiod || true) > logs/istiod.log
        (kubectl get --all-namespaces apirules.gateway.kyma-project.io -oyaml || true) > logs/apirules-dump.yaml
        (kubectl get --all-namespaces apigateways.operator.kyma-project.io -oyaml || true) > logs/gateway-dump.yaml
    - name: Uploads artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-reports-${{ github.job }}
        path: tests/integration/reports/
    - name: Uploads logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-${{ github.job }}
        path: logs/
