name: 'Integration tests (k3d)'
description: 'Runs integration tests on k3d'
inputs:
  prerequisites_target:
    description: 'Which make target to use to install prerequisites'
    required: true
  manager_image:
    description: 'Manager image used for test'
    required: true
  client_id:
    description: "Client id for oidc"
    required: true
  client_secret:
    description: "Client secret for oidc"
    required: true
  oidc_issuer_url:
    description: "OIDC issuer url"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - name: Set up environment
      shell: bash
      run: |
        sudo echo "127.0.0.1 local.kyma.dev" | sudo tee -a /etc/hosts
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | sudo bash
        [ -n "${KYMA_CLI_UNSTABLE}" ] && sudo curl -Lo /usr/bin/kyma https://storage.googleapis.com/kyma-cli-unstable/kyma-linux
        [ -z "${KYMA_CLI_UNSTABLE}" ] && sudo curl -Lo kyma.tar.gz "https://github.com/kyma-project/cli/releases/latest/download/kyma_linux_x86_64.tar.gz" && sudo tar -C /usr/bin -zxvf kyma.tar.gz kyma
        sudo chmod +x /usr/bin/kyma
    - name: Provision Kyma and run tests
      shell: bash
      env:
        KYMA_DOMAIN: "local.kyma.dev"
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
        OIDC_ISSUER_URL: ${{ inputs.oidc_issuer_url }}
        IMG: ${{ inputs.manager_image }}
      run: |
        sudo kyma provision k3d
        KUBECONFIG=$(k3d kubeconfig merge kyma) EXPORT_RESULT=true \
        make ${{ inputs.prerequisites_target }} deploy test-integration
    - name: Uploads artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-reports-${{ github.job }}
        path: tests/integration/reports/
