name: 'Integration tests (k3d)'
description: 'Runs integration tests on k3d'
inputs:
  manager_image:
    description: 'Manager image used for test'
    required: true
  client_id:
    description: "Client id for oidc"
    required: true
  client_secret:
    description: "Client secret for oidc"
    required: true
  oidc_issuer_url:
    description: "OIDC issuer url"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Checkout to PR branch # to remove after getting rid of pull_request_target
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      run: |
        git fetch origin pull/${{ github.event.number }}/head:PR-${{ github.event.number }}
        git checkout PR-${{ github.event.number }}
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "k3d-cluster"
        args: >-
          --agents 0
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --k3s-arg "--disable=traefik@server:0"
    - name: Run integration tests
      shell: bash
      env:
        KYMA_DOMAIN: "local.kyma.dev"
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
        OIDC_ISSUER_URL: ${{ inputs.oidc_issuer_url }}
        IMG: ${{ inputs.manager_image }}
      run: |
        EXPORT_RESULT=true \
        make install-istio deploy test-integration
    - name: Uploads artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-reports-${{ github.job }}
        path: tests/integration/reports/
