name: Post Main Autorelease

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-image:
    name: Build manager image
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: api-gateway/main/api-gateway-manager
      dockerfile: Dockerfile
      context: .
      build-args: |
        VERSION=main
      tags: main
