name: Prepare new minor

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Minor version (major.minor)"
        default: ""
        required: true

jobs:
  prepare-new-minor:
    name: Prepare new minor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Validate version format
        id: validate-version-format
        env:
          NEW_MINOR: ${{ inputs.version }}
        run: |
          if [[ ! "${NEW_MINOR}" =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "Version ${NEW_MINOR} does not have proper format (major.minor)!";
            exit 1
          fi

      - name: Check if release branch exists
        env:
          NEW_MINOR: ${{ inputs.version }}
        run: |
          branch_name="release-${NEW_MINOR}"
          echo "branch_name=${branch_name}" >> $GITHUB_ENV
          
          if git ls-remote --heads origin "${branch_name}" | grep -q "${branch_name}"; then
            echo "Release branch ${branch_name} already exists!"
            exit 2
          fi

      - name: Create a release branch
        run: |
          git checkout -b "${branch_name}"
          git push origin "${branch_name}"

  adjust-dependabot:
    name: Adjust dependabot
    runs-on: ubuntu-latest
    needs: [ prepare-new-minor ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update Dependabot
        env:
          NEW_MINOR: "${{ inputs.version }}"
        run: |
          ./scripts/update_release_in_dependabot.sh "${NEW_MINOR}" ".github/dependabot.yml"

      - name: Commit updated dependabot config
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ vars.ACTIONS_BOT_NAME }}
          EMAIL: ${{ vars.ACTIONS_BOT_EMAIL }}
          NEW_MINOR: ${{ inputs.version }}
        run: |
          git config user.name "${USERNAME}"
          git config user.email "${EMAIL}"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected, skipping commit"
            exit 0
          fi
          echo "Dependabot config updated, creating commit"
          git checkout -b "dependabot-config/${NEW_MINOR}"
          git commit -m "update dependabot.yml" -m "Generated by GitHub Actions"
          git push -f -u origin "dependabot-config/${NEW_MINOR}"
          echo "Creating PR"
          gh pr create --base main --head "dependabot-config/${NEW_MINOR}" --fill
