# Jobs defined in this file are responsible for things that do not require container image
# but still relevant to the codebase such as unit tests, linting etc

name: Pull Request

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'tests/performance/**'
      - 'OWNERS'
      - 'CODEOWNERS'
      - 'sec-scanners-config.yaml'
      - './github/dependabot.yml'
    branches:
      - "mod-dev"

permissions:
  contents: read

jobs:
  lint:
    name: Golang lint check
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: false # We need to disable caching here, since this is handled by the golangci-lint action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 #v3.6.0
        with:
          version: 'latest'
          args: --timeout=10m --verbose

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        run: |
          PULL_PULL_SHA=${{ github.event.pull_request.head.sha}} \
          PULL_BASE_SHA=${{ github.event.pull_request.base.sha}} \
          PULL_NUMBER=${{ github.event.number }} \
          ./tests/integration/scripts/code-coverage-guard.sh
