name: Schedule Credentials Check

permissions:
  contents: read

on:
  schedule:
    - cron: '0 6 * * *' # Run every day at 06:00 AM
  workflow_dispatch:

jobs:
  check-oidc:
    name: Check OIDC credentials
    environment:
      name: e2e
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check OIDC credentials
        env:
          OIDC_ISSUER_URL: ${{ vars.OIDC_ISSUER_URL }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-oidc.sh"

  check-gardener-token:
    name: Check Gardener token
    environment:
      name: e2e
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check Gardener token
        env:
          GARDENER_TOKEN: ${{ secrets.GARDENER_TOKEN }}
          GARDENER_PROJECT_NAME: ${{ vars.GARDENER_PROJECT_NAME }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-gardener-token.sh"

  check-gardener-apirule-access:
    name: Check Gardener APIRule access
    environment:
      name: e2e
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
      - name: Check Gardener APIRule access
        env:
          GARDENER_APIRULE_ACCESS: ${{ secrets.GARDENER_APIRULE_ACCESS }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-apirule-access.sh"

  check-dns-secret:
    name: Check DNS secret
    environment:
      name: e2e
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check DNS secret
        env:
          DNS_SA_BASE64: ${{ secrets.DNS_SECRET_JSON }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-dns-secret.sh"

  check-project-access-classic:
    name: Check GitHub project access
    environment:
      name: projects
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check GitHub project access
        env:
          GH_TOKEN: ${{ secrets.PROJECT_ACCESS_CLASSIC }}
          ORGANIZATION: kyma-project
          PROJECT_NUMBER: ${{ vars.PROJECT_ID }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-project-access.sh"

  check-slack-webhooks:
    name: Check Slack webhooks
    environment:
      name: notifications
      deployment: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check Slack webhooks
        env:
          SLACK_RELEASE_WEBHOOK: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        shell: bash
        run: "${{ github.workspace }}/hack/ci/credentials-check/check-slack-webhooks.sh"
