name: UI Tests Periodic

on:
  schedule:
    - cron: '0 5 * * 1' # run every Monday at 5:00 AM

jobs:
  run-ui-tests-periodic:
    name: Run UI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        run: |
          sudo echo "127.0.0.1 local.kyma.dev" | sudo tee -a /etc/hosts
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | sudo bash
          sha=$(./scripts/get_latest_build_sha.sh)
          docker pull europe-docker.pkg.dev/kyma-project/prod/api-gateway-manager:"$sha"
          IMG=europe-docker.pkg.dev/kyma-project/prod/api-gateway-manager:"$sha" ./tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh stage
      - uses: actions/upload-artifact@v4
        if: always()
        name: Export Cypress output
        with:
          name: cypress
          path: tests/ui/tests/cypress/

  slack_failed_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [run-ui-tests-periodic]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Notify
        uses: ./.github/actions/slack-notification-failed-workflow
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}