name: Workflow validation

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]
    paths:
      - '.github/workflows/**'
    branches:
      - main
permissions:
  contents: read

jobs:
  verify-actions:
    name: Ensure SHA pinned actions
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: zgosalvez/github-actions-ensure-sha-pinned-actions@19ebcb0babbd282ae1822a0b9c28f3f1f25cea45 # 3.0.4
        with:
          # We only want to allow official Github Actions
          allowlist: |
            actions/checkout
            actions/setup-go
            actions/upload-artifact
