name: Workflow validation

on:
  workflow_call:

permissions:
  contents: read

jobs:
  verify-actions:
    name: Ensure SHA pinned actions
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: zgosalvez/github-actions-ensure-sha-pinned-actions@b88cd0aad2c36a63e42c71f81cb1958fed95ac87 # 3.0.10
        with:
          # We only want to allow official GitHub Actions
          allowlist: |
            actions/checkout
            actions/setup-go
            actions/upload-artifact
