name: Workflow validation

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]
    paths:
      - '.github/workflows/**'
    branches:
      - main
permissions:
  contents: read

jobs:
  verify-actions:
    name: Ensure SHA pinned actions
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: zgosalvez/github-actions-ensure-sha-pinned-actions@2f2ebc6d914ab515939dc13f570f91baeb2c194c # 3.0.6
        with:
          # We only want to allow official Github Actions
          allowlist: |
            actions/checkout
            actions/setup-go
            actions/upload-artifact
