name: 'Kubernetes version compatibility check'
description: 'Runs Kubernetes version compatibility check'
inputs:
  manager_image:
    description: 'Manager image used for test'
    required: true
  client_id:
    description: "Client id for oidc"
    required: false
  client_secret:
    description: "Client secret for oidc"
    required: false
  oidc_well_known_url:
    description: "OIDC well known URL"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    - name: Checkout to PR branch # to remove after getting rid of pull_request_target
      shell: bash
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      run: |
        git fetch origin pull/${{ github.event.number }}/head:PR-${{ github.event.number }}
        git checkout PR-${{ github.event.number }}
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "test-cluster-1"
        args: >-
          --agents 2
          --image docker.io/rancher/k3s:v1.28.2-k3s1
          --servers-memory=16g
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --k3s-arg "--disable=traefik@server:0"
    - name: Provision Kyma and run tests
      shell: bash
      env:
        KYMA_DOMAIN: "local.kyma.dev"
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_SECRET: ${{ inputs.client_secret }}
        OIDC_CONFIG_URL: ${{ inputs.oidc_well_known_url }}
        IMG: ${{ inputs.manager_image }}
      run: |
        EXPORT_RESULT=true \
        make install-istio deploy test-integration
    - name: Check deprecations
      run: |
        set -eou pipefail
        GO111MODULE=on go install github.com/prometheus/prom2json/cmd/prom2json@v1.3.3
        kubectl get --context k3d-test-cluster-1 --raw /metrics | prom2json | jq '.[] | select(.name=="apiserver_requested_deprecated_apis").metrics[].labels' > deprecations.txt
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: html-reports
        path: tests/integration/reports/
    - uses: actions/upload-artifact@v4
      with:
        name: deprecation-report
        path: deprecations.txt
    - name: Check that deprecations are empty
      run: if [[ $(wc -l deprecations.txt | awk '{print $1}' ) != '0' ]]; then exit 1; fi
      shell: bash