kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Name }}
rules:
  - apiGroups: ["oathkeeper.ory.sh"]
    resources: ["rules"]
    verbs:
      - deletecollection
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
